-- Final batch: Infrastructure, Taxation, Online Services, Office Pages (24 services)
-- Completing all remaining services to reach 61/61

-- ===== INFRASTRUCTURE (3) =====
UPDATE services SET description='Request for road maintenance, repair, or improvement. Report potholes, damaged roads, or infrastructure issues.',fees='Free (public service)',processing_time='Varies (prioritized by urgency)',office='Municipal Engineering Office',steps='[{"title":"Identify Road Issue","description":"Note exact location, type of damage (pothole, cracks, flooding), and severity.","order":1},{"title":"Report to Engineering Office","description":"Visit Municipal Engineering Office or report via hotline. Provide location and photos if possible.","order":2},{"title":"Assessment","description":"Engineering team will assess and prioritize based on severity and traffic volume.","order":3},{"title":"Scheduling","description":"Repair will be scheduled based on priority and budget availability.","order":4},{"title":"Completion","description":"Road maintenance will be completed. Major repairs may take weeks to months.","order":5}]'::jsonb,faq='[{"question":"How long does road repair take?","answer":"Minor repairs (potholes): days to weeks. Major repairs: weeks to months. Depends on severity, budget, and weather.","order":1}]'::jsonb,office_details='{"name":"Municipal Engineering Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"road_maintenance_request":["Location of road issue","Description of problem","Photos (if available)","Contact information"]}'::jsonb,related_services=ARRAY['building-permit'] WHERE slug='road-maintenance-request';

UPDATE services SET description='Municipal Engineering Office handles infrastructure projects, building permits, road maintenance, and engineering services.',fees='Varies by service',processing_time='Varies by service',office='Municipal Engineering Office',steps='[{"title":"Visit Engineering Office","description":"Located at City Hall. Consult for building permits, road issues, and infrastructure concerns.","order":1}]'::jsonb,faq='[{"question":"What services does Engineering Office provide?","answer":"Building permits, occupancy permits, road maintenance, infrastructure projects, engineering consultations.","order":1}]'::jsonb,office_details='{"name":"Municipal Engineering Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID for transactions"]}'::jsonb,related_services=ARRAY['building-permit','occupancy-permit','road-maintenance-request'] WHERE slug='municipal-engineering-office';

UPDATE services SET description='Municipal Planning and Development Office handles city planning, zoning, development projects, and comprehensive land use planning.',fees='Varies by service',processing_time='Varies by service',office='Municipal Planning and Development Office',steps='[{"title":"Visit Planning Office","description":"Located at City Hall. Consult for zoning, development plans, and city planning matters.","order":1}]'::jsonb,faq='[{"question":"What does Planning Office do?","answer":"City planning, zoning regulations, development permits, comprehensive land use planning, project monitoring.","order":1}]'::jsonb,office_details='{"name":"Municipal Planning and Development Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID for transactions"]}'::jsonb,related_services=ARRAY['building-permit','environmental-clearance'] WHERE slug='municipal-planning-development-office';

-- ===== TAXATION (7) =====
UPDATE services SET description='Annual business tax payment based on gross sales/receipts. Required for all businesses operating in Ormoc City.',fees='Based on gross sales (1-2% typically)',processing_time='Same day',office='City Treasurer Office',steps='[{"title":"Prepare Financial Records","description":"Gather gross sales/receipts records for the year. Compute taxable amount.","order":1},{"title":"Fill Out Tax Return","description":"Complete business tax return form. Declare gross sales accurately.","order":2},{"title":"Submit to Treasurer","description":"Go to City Treasurer Office. Submit tax return with supporting documents.","order":3},{"title":"Pay Business Tax","description":"Pay computed business tax. Get official receipt.","order":4},{"title":"Keep Records","description":"Keep tax return and receipt for business permit renewal and future reference.","order":5}]'::jsonb,faq='[{"question":"When is business tax due?","answer":"Usually paid with business permit renewal (before January 20). Quarterly payment also allowed.","order":1}]'::jsonb,office_details='{"name":"City Treasurer Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"business_tax":["Business Permit","Financial records (gross sales/receipts)","Tax return form","Valid ID","Payment"]}'::jsonb,related_services=ARRAY['business-permit','tax-clearance'] WHERE slug='business-tax-payment';

UPDATE services SET description='Declaration of real property for tax assessment purposes. Required for all land and building owners.',fees='₱100-₱200',processing_time='3-5 business days',office='City Assessor Office',steps='[{"title":"Prepare Property Documents","description":"Bring land title, deed of sale, or other proof of ownership.","order":1},{"title":"Submit Declaration","description":"Go to Assessor Office. Submit property declaration form with documents.","order":2},{"title":"Property Inspection","description":"Assessor may inspect property to determine value and classification.","order":3},{"title":"Receive Tax Declaration","description":"Get Tax Declaration with assessed value. Use for property tax payment.","order":4}]'::jsonb,faq='[{"question":"When should I declare property?","answer":"Within 60 days of acquisition (purchase, inheritance, donation). Also when improvements are made.","order":1}]'::jsonb,office_details='{"name":"City Assessor Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"new_property":["Land Title or Deed of Sale","Tax Declaration of previous owner (if available)","Valid ID","Payment for declaration fee"],"improvement":["Current Tax Declaration","Building Permit and Occupancy Permit","Valid ID","Payment"]}'::jsonb,related_services=ARRAY['real-property-tax','building-permit'] WHERE slug='property-declaration';

UPDATE services SET description='Municipal Treasurer Office handles tax collection, payments, and treasury services.',fees='Varies by service',processing_time='Varies',office='Municipal Treasurer Office',steps='[{"title":"Visit Treasurer Office","description":"Ground floor, City Hall. For tax payments and treasury services.","order":1}]'::jsonb,faq='[{"question":"What services available?","answer":"Real property tax, business tax, tax clearance, payments, treasury services.","order":1}]'::jsonb,office_details='{"name":"Municipal Treasurer Office","location":"City Hall, Ground Floor","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['real-property-tax','business-tax-payment','tax-clearance'] WHERE slug='municipal-treasurer-s-office';

UPDATE services SET description='Municipal Assessor Office handles property assessment, tax declaration, and real property valuation.',fees='Varies',processing_time='Varies',office='Municipal Assessor Office',steps='[{"title":"Visit Assessor Office","description":"City Hall. For property assessment and tax declaration.","order":1}]'::jsonb,faq='[{"question":"What does Assessor do?","answer":"Property assessment, tax declaration, real property valuation, property records.","order":1}]'::jsonb,office_details='{"name":"Municipal Assessor Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['property-declaration','real-property-tax'] WHERE slug='municipal-assessor-s-office';

UPDATE services SET description='Municipal Budget Office handles budget preparation, monitoring, and financial planning.',fees='N/A',processing_time='N/A',office='Municipal Budget Office',steps='[{"title":"Visit Budget Office","description":"City Hall. For budget-related inquiries.","order":1}]'::jsonb,faq='[{"question":"What does Budget Office do?","answer":"Budget preparation, financial planning, budget monitoring, fiscal management.","order":1}]'::jsonb,office_details='{"name":"Municipal Budget Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['municipal-accounting-office'] WHERE slug='municipal-budget-office';

UPDATE services SET description='Municipal Accounting Office handles accounting, financial reporting, and disbursements.',fees='N/A',processing_time='N/A',office='Municipal Accounting Office',steps='[{"title":"Visit Accounting Office","description":"City Hall. For accounting and financial matters.","order":1}]'::jsonb,faq='[{"question":"What does Accounting Office do?","answer":"Financial accounting, reporting, disbursements, payroll, financial records.","order":1}]'::jsonb,office_details='{"name":"Municipal Accounting Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['municipal-budget-office','municipal-treasurer-s-office'] WHERE slug='municipal-accounting-office';

UPDATE services SET description='Real property tax payment online through authorized payment channels.',fees='Based on assessed property value',processing_time='Real-time',office='Online / City Treasurer Office',steps='[{"title":"Check if Available","description":"Verify if Ormoc City offers online property tax payment.","order":1},{"title":"Register Online","description":"Create account on city payment portal if required.","order":2},{"title":"Enter Property Details","description":"Input Tax Declaration Number or property details.","order":3},{"title":"Review Amount","description":"Verify tax amount, penalties (if any), and total.","order":4},{"title":"Pay Online","description":"Pay via credit card, debit card, or online banking.","order":5},{"title":"Get Receipt","description":"Save/print official receipt for records.","order":6}]'::jsonb,faq='[{"question":"Is online payment available?","answer":"Check with City Treasurer if online payment is available for Ormoc City.","order":1}]'::jsonb,office_details='{"name":"City Treasurer Office / Online Portal","location":"Online or City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Online: 24/7 / Office: Mon-Fri 8AM-5PM"}'::jsonb,requirements_by_type='{"online_payment":["Tax Declaration Number","Property details","Payment method (credit/debit card, online banking)","Email for receipt"]}'::jsonb,related_services=ARRAY['real-property-tax','property-declaration'] WHERE slug='real-property-tax-online-billing-payment';

-- ===== ONLINE SERVICES (4) =====
UPDATE services SET description='Online billing and payment for business taxes and permits.',fees='Varies',processing_time='Real-time',office='Online Portal',steps='[{"title":"Check Availability","description":"Verify if online business payment is available.","order":1},{"title":"Access Portal","description":"Go to city online payment portal.","order":2},{"title":"Login/Register","description":"Create account or login.","order":3},{"title":"Select Service","description":"Choose business tax/permit payment.","order":4},{"title":"Pay Online","description":"Complete payment via online channels.","order":5},{"title":"Get Receipt","description":"Save official receipt.","order":6}]'::jsonb,faq='[{"question":"Is this available?","answer":"Check with Business Permits Office for online payment availability.","order":1}]'::jsonb,office_details='{"name":"Online Portal / Business Permits Office","location":"Online or City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Online: 24/7 / Office: Mon-Fri 8AM-5PM"}'::jsonb,requirements_by_type='{"online":["Business details","Payment method","Email"]}'::jsonb,related_services=ARRAY['business-permit','business-permit-renewal'] WHERE slug='business-online-billing-payment';

UPDATE services SET description='Online renewal of business permit.',fees='Varies',processing_time='1-3 days',office='Online Portal',steps='[{"title":"Access Portal","description":"Go to online business permit portal if available.","order":1},{"title":"Login","description":"Use business account credentials.","order":2},{"title":"Submit Renewal","description":"Upload requirements and submit online.","order":3},{"title":"Pay Online","description":"Pay renewal fees online.","order":4},{"title":"Claim Permit","description":"Claim renewed permit at office or via delivery if available.","order":5}]'::jsonb,faq='[{"question":"Available online?","answer":"Check with Business Permits Office for online renewal system.","order":1}]'::jsonb,office_details='{"name":"Online Portal / Business Permits Office","location":"Online or City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Online: 24/7 / Office: Mon-Fri 8AM-5PM"}'::jsonb,requirements_by_type='{"online":["Business account","Requirements (digital)","Payment method"]}'::jsonb,related_services=ARRAY['business-permit-renewal','business-permit'] WHERE slug='business-permit-renewal-online';

UPDATE services SET description='Online application for new business permit.',fees='Varies',processing_time='3-7 days',office='Online Portal',steps='[{"title":"Register Business Name","description":"Register with DTI/SEC first.","order":1},{"title":"Access Portal","description":"Go to online business application portal if available.","order":2},{"title":"Fill Application","description":"Complete online application form.","order":3},{"title":"Upload Requirements","description":"Submit digital copies of requirements.","order":4},{"title":"Pay Online","description":"Pay application fees online.","order":5},{"title":"Schedule Inspection","description":"Coordinate for business inspection.","order":6},{"title":"Claim Permit","description":"Claim approved permit at office.","order":7}]'::jsonb,faq='[{"question":"Fully online?","answer":"Application may be online but inspection and claiming still require office visit.","order":1}]'::jsonb,office_details='{"name":"Online Portal / Business Permits Office","location":"Online or City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Online: 24/7 / Office: Mon-Fri 8AM-5PM"}'::jsonb,requirements_by_type='{"online":["DTI/SEC registration","Requirements (digital)","Payment method"]}'::jsonb,related_services=ARRAY['business-permit','business-permit-renewal-online'] WHERE slug='new-business-application-online';

UPDATE services SET description='Online payment order system for various city services.',fees='Varies',processing_time='Real-time',office='Online Portal',steps='[{"title":"Access Portal","description":"Go to city online payment portal.","order":1},{"title":"Select Service","description":"Choose service to pay for.","order":2},{"title":"Generate Order","description":"System generates payment order.","order":3},{"title":"Pay Online","description":"Complete payment.","order":4},{"title":"Get Receipt","description":"Save official receipt.","order":5}]'::jsonb,faq='[{"question":"What can I pay online?","answer":"Depends on city system. May include taxes, permits, fees. Check portal for available services.","order":1}]'::jsonb,office_details='{"name":"Online Payment Portal","location":"Online","address":"Check city website","phone":"+63 53 561 6000","hours":"24/7 Online"}'::jsonb,requirements_by_type='{"online":["Service details","Payment method","Email"]}'::jsonb,related_services=ARRAY['real-property-tax-online-billing-payment','business-online-billing-payment'] WHERE slug='online-payment-order';

-- ===== OFFICE PAGES & FACILITIES (10) =====
UPDATE services SET description='General Services Office handles facilities management, supplies, equipment, and general administrative services.',fees='N/A',processing_time='N/A',office='General Services Office',steps='[{"title":"Visit GSO","description":"City Hall. For facilities and equipment concerns.","order":1}]'::jsonb,faq='[{"question":"What does GSO do?","answer":"Facilities management, supplies, equipment, maintenance, general administrative services.","order":1}]'::jsonb,office_details='{"name":"General Services Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY[] WHERE slug='general-services-office';

UPDATE services SET description='Human Resource Management Office handles personnel, recruitment, employee benefits, and HR services.',fees='N/A',processing_time='N/A',office='Human Resource Management Office',steps='[{"title":"Visit HRMO","description":"City Hall. For employment and HR matters.","order":1}]'::jsonb,faq='[{"question":"What does HRMO do?","answer":"Personnel management, recruitment, employee benefits, training, HR services.","order":1}]'::jsonb,office_details='{"name":"Human Resource Management Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY[] WHERE slug='human-resource-management-office';

UPDATE services SET description='Local Civil Registrar Office handles vital records: birth, death, marriage certificates and registration.',fees='Varies',processing_time='Varies',office='Local Civil Registrar',steps='[{"title":"Visit LCR","description":"2nd Floor, City Hall. For civil registry services.","order":1}]'::jsonb,faq='[{"question":"What services available?","answer":"Birth, death, marriage certificates, registration of vital events, CENOMAR.","order":1}]'::jsonb,office_details='{"name":"Local Civil Registrar","location":"City Hall, 2nd Floor","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['birth-certificate','death-certificate','marriage-certificate','cenomar'] WHERE slug='local-civil-registrar';

UPDATE services SET description='Business Permits and Licensing Office handles all business permit applications, renewals, and business-related permits.',fees='Varies',processing_time='Varies',office='Business Permits and Licensing Office',steps='[{"title":"Visit Business Permits Office","description":"City Hall. For business permit services.","order":1}]'::jsonb,faq='[{"question":"What services?","answer":"New business permits, renewals, amendments, business closure, business-related clearances.","order":1}]'::jsonb,office_details='{"name":"Business Permits and Licensing Office","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['business-permit','business-permit-renewal','business-closure'] WHERE slug='business-permits-licensing-office';

UPDATE services SET description='Municipal Social Welfare and Development Office provides social services, assistance programs, and welfare services.',fees='Varies',processing_time='Varies',office='MSWDO / CSWDO',steps='[{"title":"Visit MSWDO","description":"City Hall. For social welfare services.","order":1}]'::jsonb,faq='[{"question":"What services?","answer":"Financial assistance, PWD/Senior/Solo Parent IDs, social welfare programs, crisis intervention.","order":1}]'::jsonb,office_details='{"name":"Municipal Social Welfare and Development Office (MSWDO/CSWDO)","location":"City Hall","address":"Ormoc City, Leyte","phone":"+63 53 561 6000","hours":"Monday to Friday: 8:00 AM - 5:00 PM"}'::jsonb,requirements_by_type='{"general":["Valid ID"]}'::jsonb,related_services=ARRAY['financial-assistance','pwd-id-services','senior-citizen-id','solo-parent-id'] WHERE slug='mswdo-services';

UPDATE services SET description='SEEDO Public Market - city public market for fresh produce, meat, fish, and general merchandise.',fees='Stall rental varies',processing_time='N/A',office='SEEDO Public Market',steps='[{"title":"Visit Public Market","description":"Located in city center. Operating hours vary by section.","order":1}]'::jsonb,faq='[{"question":"Market hours?","answer":"Generally 5AM-6PM daily. Some sections 24 hours. Wet market busiest early morning.","order":1}]'::jsonb,office_details='{"name":"SEEDO Public Market","location":"City Center","address":"Ormoc City, Leyte","phone":"Contact market administration","hours":"Daily: 5:00 AM - 6:00 PM (varies by section)"}'::jsonb,requirements_by_type='{"vendor":["Business permit","Sanitary permit","Stall rental payment"]}'::jsonb,related_services=ARRAY['business-permit','sanitary-permit'] WHERE slug='seedo-public-market';

UPDATE services SET description='SEEDO Slaughterhouse - city slaughterhouse for meat processing and inspection.',fees='Slaughter fees vary by animal',processing_time='Same day',office='SEEDO Slaughterhouse',steps='[{"title":"Bring Livestock","description":"Bring livestock to slaughterhouse. Operating hours early morning.","order":1},{"title":"Pay Slaughter Fee","description":"Pay slaughter fee based on animal type and weight.","order":2},{"title":"Meat Inspection","description":"Meat will be inspected by city veterinarian.","order":3},{"title":"Collect Meat","description":"Collect processed meat after inspection and approval.","order":4}]'::jsonb,faq='[{"question":"Slaughter fees?","answer":"Varies by animal type (pig, cow, goat, etc.) and weight. Check with slaughterhouse for current rates.","order":1}]'::jsonb,office_details='{"name":"SEEDO Slaughterhouse","location":"Check with city for location","address":"Ormoc City, Leyte","phone":"Contact slaughterhouse","hours":"Early morning operations"}'::jsonb,requirements_by_type='{"slaughter":["Livestock","Payment for slaughter fee","Proof of ownership (if required)"]}'::jsonb,related_services=ARRAY['sanitary-permit','health-certificate'] WHERE slug='seedo-slaughterhouse';

-- Duplicate cleanup - these are duplicates, just update minimally
UPDATE services SET description='Community Tax Certificate (Cedula) - basic tax document. See main Community Tax Certificate service for details.',fees='₱5 minimum',processing_time='15-30 minutes',office='Barangay Hall or Municipal Treasurer',related_services=ARRAY['community-tax-certificate','barangay-clearance'] WHERE slug='community-tax-certificate-cedula';

UPDATE services SET description='Business Permit (New) - see main Business Permit service for complete details.',fees='Varies',processing_time='3-7 business days',office='Business Permits Office',related_services=ARRAY['business-permit','business-permit-renewal'] WHERE slug='business-permit-new';

UPDATE services SET description='Real Property Tax Payment - see main Real Property Tax service for complete details.',fees='Based on assessed value',processing_time='15-30 minutes',office='City Treasurer Office',related_services=ARRAY['real-property-tax','property-declaration'] WHERE slug='real-property-tax-payment';
